---
# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false

# PDP
pdp:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75

# ROBOT SUBSYSTEMS
subsystems:
  # ROBOT DRIVE
  - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
      '@id': drive
      #Wheelbase: 2.16810362021
      leftMaster:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
          &leftMaster
          '@id': leftMaster
          name: left
          port: 1
          PDP:
            org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
          voltagePerCurrentLinReg:
            bufferSize: 250
            rSquaredThreshhold: 0.75
          reverseOutput: true
          reverseSensor: false
          enableBrakeMode: true
          postEncoderGearing: 0.2266546
          feetPerRotation: 1.042920176494184
          currentLimit: 35
          enableVoltageComp: true
          feedbackDevice: QuadEncoder
          encoderCPR: 256
          startingGear: LOW
          perGearSettings:
            - &lowGear
              gear: LOW
              feedForwardComponent:
                org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.feedForwardComponent.FeedForwardKaKvComponent:
                  kAFwd: 0.12919953323
                  kVFwd: 1.32498443423
                  interceptVoltageFwd: 0.797588
                  kARev: 0.15941277553
                  kVRev: 1.28936521731
                  interceptVoltageRev: 0.7743393
              maxSpeed: 4
              kP: 0.15
              motionProfilePFwd: 0.5
            - &highGear
              gear: HIGH
              feedForwardComponent:
                org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.feedForwardComponent.FeedForwardKaKvComponent:
                  kAFwd: 0.19423682134
                  kVFwd: 0.65106152446
                  interceptVoltageFwd: 0.986742
                  kARev: 0.20714931484
                  kVRev: 0.63105309
                  interceptVoltageRev: 0.894144
              maxSpeed: 4
              kP: 0.3
          minNumPointsInBottomBuffer: 10
          updaterProcessPeriodSecs: 0.005
          statusFrameRatesMillis: !!map
            Status_4_AinTempVbat : 15
          slaveVictors:
            - org.usfirst.frc.team449.robot.jacksonWrappers.SlaveTalon:
                port: 2
                inverted: true
            - org.usfirst.frc.team449.robot.jacksonWrappers.SlaveTalon:
                port: 3
                inverted: true
      rightMaster:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
          <<: *leftMaster
          '@id': rightMaster
          name: right
          port: 4
          reverseOutput: false
          reverseSensor: false
          perGearSettings:
            - <<: *lowGear
              feedForwardComponent:
                org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.feedForwardComponent.FeedForwardKaKvComponent:
                  kAFwd: 0.1131952403
                  kVFwd: 1.32948238154
                  interceptVoltageFwd: 0.793247
                  kARev: 0.12721050276
                  kVRev: 1.29887888885
                  interceptVoltageRev: 0.7668543
            - <<: *highGear
              feedForwardComponent:
                org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.feedForwardComponent.FeedForwardKaKvComponent:
                  kAFwd: 0.19440692065
                  kVFwd: 0.63537039069
                  interceptVoltageFwd: 0.997928
                  kARev: 0.19604213688
                  kVRev: 0.62924298023
                  interceptVoltageRev: 0.8839750
          slaveVictors:
            -  org.usfirst.frc.team449.robot.jacksonWrappers.SlaveTalon:
                 port: 12o
                 inverted: false
            - org.usfirst.frc.team449.robot.jacksonWrappers.SlaveTalon:
                port: 6
                inverted: false
      startingOverrideAutoshift: false
      ahrs:
        org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS:
          '@id': navX
          port: kMXP
          invertYaw: true
      shiftComponent:
        org.usfirst.frc.team449.robot.components.ShiftComponent:
          '@id': driveShiftComponent
          otherShiftables:
            - org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
                leftMaster
            - org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
                rightMaster
          piston:
            '@id': driveShifter
            forward: 4
            reverse: 5
          startingGear: LOW
# COMMANDS
commands:
  defaultCommands:
    # DEFAULT DRIVE COMMAND
    - org.usfirst.frc.team449.robot.commands.multiInterface.drive.UnidirectionalNavXShiftingDefaultDrive:
        '@id': defaultDriveCommand
        kP: 0.0075
        kI: 0.0
        kD: 0.03
        absoluteTolerance: 0
        deadband: 2
        maxAngularVelToEnterLoop: 15
        inverted: false
        highGearAngularCoefficient: 2
        rampComponent:
          org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.RampComponent:
            maxChangePerSecond: 3
        driveStraightLoopEntryTimer:
          '@id': driveStraightLoopEntryTimer
          bufferTimeSeconds: 0.15
        subsystem:
          org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
            drive
        oi:
          org.usfirst.frc.team449.robot.oi.unidirectional.OIOutreach:
            '@id': oi
            overridenOI:
              org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad:
                '@id': overriden
                gamepad:
                  org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
                    '@id': kidGamepad
                    port: 2
                rotThrottle:
                  org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                    &overridenRotThrottle
                    '@id': overridenRotThrottle
                    stick: kidGamepad
                    axis: 0
                    smoothingTimeSecs: 0.04
                    deadband: 0.075
                    inverted: false
                    polynomial:
                      org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                        '@id': overridenRotPoly
                        powerToCoefficientMap: !!map
                          1 : 1
                          3 : 2
                fwdThrottle:
                  org.usfirst.frc.team449.robot.oi.throttles.ThrottleSum:
                    '@id': overridenFwdThrottle
                    throttles:
                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                          <<: *overridenRotThrottle
                          '@id': overridenPosThrottle
                          axis: 3
                          inverted: false
                          deadband: 0.05
                          polynomial:
                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                              '@id': overridenPosPoly
                              powerToCoefficientMap: !!map
                                2 : 1
                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                          <<: *overridenRotThrottle
                          '@id': overridenNegThrottle
                          axis: 2
                          inverted: true
                          deadband: 0.05
                          polynomial:
                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                              '@id': overridenNegPoly
                              powerToCoefficientMap: !!map
                                2 : 1
                invertDPad: false
                dPadShift: 0.1
                turnInPlaceRotScale: 0.3
                rescaleOutputs: true
                scaleRotByFwdPoly:
                  org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                    '@id': overridenScaleRotByFwdPoly
                    powerToCoefficientMap: !!map
                      #0.5: 0.6
                      0: 0.2
                      1 : 0.75
            overridingOI:
              org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad:
                '@id': overriding
                gamepad:
                  org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
                    '@id': driverGamepad
                    port: 1
                rotThrottle:
                  org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                    &rotThrottle
                    '@id': rotThrottle
                    stick: driverGamepad
                    axis: 0
                    smoothingTimeSecs: 0.04
                    deadband: 0.075
                    inverted: false
                    polynomial:
                      org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                        '@id': rotPoly
                        powerToCoefficientMap: !!map
                          1 : 1
                          3 : 2
                fwdThrottle:
                  org.usfirst.frc.team449.robot.oi.throttles.ThrottleSum:
                    '@id': fwdThrottle
                    throttles:
                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                          <<: *rotThrottle
                          '@id': posThrottle
                          axis: 3
                          inverted: false
                          deadband: 0.05
                          polynomial:
                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                              '@id': posPoly
                              powerToCoefficientMap: !!map
                                2 : 1
                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                          <<: *rotThrottle
                          '@id': negThrottle
                          axis: 2
                          inverted: true
                          deadband: 0.05
                          polynomial:
                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                              '@id': negPoly
                              powerToCoefficientMap: !!map
                                2 : 1
                invertDPad: false
                dPadShift: 0.1
                turnInPlaceRotScale: 0.3
                rescaleOutputs: true
                scaleRotByFwdPoly:
                  org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                    '@id': scaleRotByFwdPoly
                    powerToCoefficientMap: !!map
                      #0.5: 0.6
                      0: 0.2
                      1 : 0.75
            button:
              org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
                '@id': overrideButton
                joystick:
                  org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
                    driverGamepad
                buttonNumber: 1
        autoshiftComponent:
          '@id': autoshiftComponent
          upshiftSpeed: 5.5
          downshiftSpeed: 3
          upshiftDebouncer:
            '@id': upshiftDebouncer
            bufferTimeSeconds: 0.06
          upshiftFwdThresh: 0.4
  #BUTTONS
  buttons:
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': releaseHatchButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              driverGamepad
          buttonNumber: 2
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.commands.SolenoidReverse:
          '@id': releaseHatch
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.SolenoidSimple:
              '@id': hatchSolenoid
              piston:
                '@id': hatchPiston
                module: 0
                forward: 5
                reverse: 4
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': secureHatchButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              driverGamepad
          buttonNumber: 3
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.commands.SolenoidForward:
          '@id': secureHatch
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.SolenoidSimple:
              hatchSolenoid
      action: WHEN_PRESSED
#    - button: # TODO figure out on drivergamepad
#        org.usfirst.frc.team449.robot.oi.buttons.TriggerButton:
#          '@id': extendHatchMechButton
#          triggerAt: 0.5
#          throttle:
#            org.usfirst.frc.team449.robot.oi.throttles.ThrottleBasic:
#              '@id': mechRightTrigger
#              axis: 2
#              stick:
#                org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
#                  mechanismsGamepad
#      command:
#        org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.commands.SolenoidForward:
#          '@id': extendHatchMech
#          subsystem:
#            org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.SolenoidSimple:
#              '@id': hatchMechExtenderSolenoid
#              piston:
#                '@id': hatchMechExtenderPiston
#                module: 0
#                forward: 3
#                reverse: 2
#      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': cargoIntakeButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsGamepad
          buttonNumber: 4
      command:
        org.usfirst.frc.team449.robot.commands.general.CommandSequence:
          '@id': lowerArmAndIntake
          commandList:
            - org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
                '@id': cargoIntakeCommand
                subsystem:
                  org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
                    '@id': cargoSubsystem
                    motor:
                      org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
                        '@id': cargoMotor
                        port: 11
                        enableBrakeMode: false
                        enableVoltageComp: true
                        currentLimit: 30
                        reverseOutput: false
                    inFastVel: -1
                    inSlowVel: -0.2
                    outFastVel: 1
                mode: IN_FAST
            - org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.commands.SolenoidForward:
                '@id': cargoArmDownCommand1
                subsystem:
                  org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.SolenoidSimple:
                    '@id': cargoArmSolenoid
                    piston:
                      '@id': cargoArmPiston
                      module: 1
                      forward: 3
                      reverse: 2
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          cargoIntakeButton
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
          '@id': cargoIntakeOff
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
             cargoSubsystem
          mode: IN_SLOW
      action: WHEN_RELEASED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': cargoOutButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsGamepad
          buttonNumber: 5 # TODO figure out
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
          '@id': cargoOutCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
              cargoSubsystem
          mode: OUT_FAST
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          cargoOutButton
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
          '@id': cargoOutOff
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
              cargoSubsystem
          mode: "OFF"
      action: WHEN_RELEASED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': cargoArmUpButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsGamepad
          buttonNumber: 5
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.commands.SolenoidReverse:
          '@id': cargoArmUpCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.SolenoidSimple:
              cargoArmSolenoid
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': cargoArmDownButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsGamepad
          buttonNumber: 6
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.commands.SolenoidForward:
          '@id': cargoArmDownCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.SolenoidSimple:
              cargoArmSolenoid
      action: WHEN_PRESSED
# UPDATER
updater:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
      - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
      - org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad: oi
      - org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS: navX
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
