---
# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false

# PDP
pdp:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75

# ROBOT SUBSYSTEMS
subsystems:
  # SHOOTER
  - org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
      '@id': shooterFlywheel
      shooterMotor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSSparkMax:
          '@id': shooterMotor
          port: 1 #TODO
          name: shooterMotor
          reverseOutput: false
          enableBrakeMode: false
          PDP: PDP
          postEncoderGearing: 1 #TODO
          feetPerRotation: 1.0472 #TODO
          currentLimit: 5 #TODO
          enableVoltageComp: true #TODO
          perGearSettings:
            - gearNum: 0
#              maxSpeed: 100 #uncomment for fps velocity control
              kP: 0.003
              kI: 0.0
              kD: 0.05
          startingGearNum: 0 #TODO
          slaveSparks:
            - port: 2
              invert: true
      shooterThrottle: -0.3 #percent out
      feederMotor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon: #TODO TODO
          '@id': kickerTalon
          port: 3
          name: kickerTalon
          reverseOutput: false
          enableBrakeMode: false
          PDP: PDP
          currentLimit: 10 #TODO
          reverseSensor: false #TODO
      feederThrottle: 0 #TODO

# COMMANDS
commands:
  #BUTTONS
  buttons:
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': shooterStartButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              '@id': mechanismsJoystick
              port: 0
          buttonNumber: 1 #A
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.SpinUpThenShoot:
          '@id': shootCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
              shooterFlywheel
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': shooterStopButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 2 #B
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.TurnAllOff:
          '@id': shooterStopCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
              shooterFlywheel
      action: WHEN_PRESSED


# UPDATER
updater:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
      #      - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
      #      - org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad: oi
      #      - org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS: navX
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
