---
# WHETHER TO USE THE CAMERA SERVER
useCameraServer: true

# PDP
pdp:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75

subsystems:
  - org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
      '@id': intake
      motor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
          &amotor
          '@id': amotor
          name: themotor
          port: 1
          PDP:
            org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
          voltagePerCurrentLinReg:
            bufferSize: 250
            rSquaredThreshhold: 0.75
          reverseOutput: false
          reverseSensor: false
          enableBrakeMode: true
          postEncoderGearing: 0.13333333333
          feetPerRotation: 1.556344647
          currentLimit: 35
          enableVoltageComp: true
          feedbackDevice: kQuadrature
          encoderCPR: 256
          startingGear: LOW
          perGearSettings:
              gear: LOW
              maxSpeed: 7.0
              kP: 0.15
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.960891
                  kV: 1.433226
                  kA: 0.165688
            - &highGear
              gear: HIGH
              maxSpeed: 14
              kP: 0.3
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 1.40187
                  kV: 0.59688
                  kA: 0.15676
          updaterProcessPeriodSecs: 0.005
      inSlowVel: 0.1
      inFastVel: 0.2
      outSlowVel: -0.1
      outFastVel: -0.2

buttons:
  - button:
      org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
        '@id': intakeStartButton
        stick:
          org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              '@id': mechanismsGamepad
              port: 2
        buttonNumber: 3 #X:
    command:
      org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
        '@id': intakeStartCommand
        subsystem:
          org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
            intake
        mode: IN_SLOW
  - button:
      org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
        '@id': intakeStopButton
        joystick:
          org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
            mechanismsGamepad
        buttonNumber: 4 #Y:
    command:
      org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
        '@id': intakeStopCommand
        subsystem:
          org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
            intake
        mode: OFF

#  autoStartupCommand:
#    org.usfirst.frc.team449.robot.commands.multiInterface.drive.RamseteControllerUnidirectionalDrive:
#      '@id':testDriveCommand
#      drivetrain:
#        org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
#      P: 0.15
#      D: 0

# UPDATER
updater:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
      - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
      - org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad: oi
      - org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS: navX
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP