---
# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false

# PDP
pdp:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75

# ROBOT SUBSYSTEMS
subsystems:
  # ROBOT DRIVE
  - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
      '@id': drive
      #Wheelbase: 2.14
      leftMaster:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
          &leftMaster
          '@id': leftMaster
          name: left
          port: 2
          PDP:
            org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
          voltagePerCurrentLinReg:
            bufferSize: 250
            rSquaredThreshhold: 0.75
          reverseOutput: true
          reverseSensor: false
          enableBrakeMode: true
          postEncoderGearing: 0.13333333333
          feetPerRotation: 1.556344647
          currentLimit: 35
          enableVoltageComp: true
          feedbackDevice: QuadEncoder
          encoderCPR: 256
          startingGear: LOW
          perGearSettings:
            - &lowGear
              gear: LOW
              maxSpeed: 7.0
              kP: 0.15
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.960891
                  kV: 1.433226
                  kA: 0.165688
            - &highGear
              gear: HIGH
              maxSpeed: 14
              kP: 0.3
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 1.40187
                  kV: 0.59688
                  kA: 0.15676
          updaterProcessPeriodSecs: 0.005
          statusFrameRatesMillis: !!map
            Status_4_AinTempVbat: 15
          slaveVictors:
            - port: 4
              invertType: FollowMaster
            - port: 6
              invertType: FollowMaster
      rightMaster:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
          <<: *leftMaster
          '@id': rightMaster
          name: right
          port: 1
          reverseOutput: false
          reverseSensor: false
          perGearSettings:
            - <<: *lowGear
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0.959980
                  kV: 1.460269
                  kA: 0.224505
            - <<: *highGear
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 1.400309
                  kV: 0.631419
                  kA: 0.151538
          slaveVictors:
            - port: 3
              #inverted: false
            - port: 5
              #inverted: false
      startingOverrideAutoshift: false
      ahrs:
        org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS:
          '@id': navX
          port: kMXP
          invertYaw: true
      trackWidthMeters: 0.6
      shiftComponent:
        org.usfirst.frc.team449.robot.components.ShiftComponent:
          '@id': driveShiftComponent
          otherShiftables:
            - org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
                leftMaster
            - org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon:
                rightMaster
          piston:
            '@id': driveShifter
            module: 0
            forward: 0
            reverse: 1
          startingGear: LOW
  # SHOOTER
  - org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
      '@id': shooterFlywheel
      shooterMotor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSSparkMax:
          '@id': shooterMotor
          port: 1 #TODO
          name: rightMotor
          inverted: true
          enableBrakeMode: true
          PDP: PDP
          enableVoltageComp: true #TODO
          perGearSettings:
          - gearNum: 0
            feedForwardCalculator:
              org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                kS: 0
                kV: 0.126
                kA: 0
            maxSpeed: 90 #rps
            kP: 0 #0.0001
            kI: 0.
            kD: 0
          startingGearNum: 0 #TODO
      otherShooterMotor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSSparkMax:
          '@id': shooterMotor2
          port: 2 #TODO
          name: leftMotor
          inverted: false
          enableBrakeMode: true
          PDP: PDP
          enableVoltageComp: true #TODO
          perGearSettings:
            - gearNum: 0
              feedForwardCalculator:
                org.usfirst.frc.team449.robot.jacksonWrappers.FeedForwardCalculators.MappedFeedForwardCalculator:
                  kS: 0
                  kV: 0.126
                  kA: 0
              maxSpeed: 90 #rps
              kP: 0 #0.0001
              kI: 0
              kD: 0
          startingGearNum: 0 #TODO
      shooterThrottle: .55 #percent
      kickerMotor:
        org.usfirst.frc.team449.robot.generalInterfaces.simpleMotor.MappedVictorSPX: #TODO TODO
          '@id': kickerVictor
          port: 7
          inverted: false
          brakeMode: false
      kickerThrottle: 1 #percent
  # FEEDER
  - org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
      '@id': feeder
      motor:
        org.usfirst.frc.team449.robot.jacksonWrappers.FPSTalon: #TODO TODO
          '@id': feederMotor
          port: 8 #TODO
          name: feederMotor
          reverseOutput: false
          enableBrakeMode: false
          PDP: PDP
          currentLimit: 10 #TODO
          reverseSensor: false #TODO
          startingGearNum: 0 #TODO
      inSlowVel: 0
      inFastVel: 0.15
      outSlowVel: -0.1
      outFastVel: -0.2



# COMMANDS
commands:
  defaultCommands:
    # DEFAULT DRIVE COMMAND
    - subsystem:
        org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
          drive
      command:
        org.usfirst.frc.team449.robot.commands.multiInterface.drive.UnidirectionalNavXShiftingDefaultDrive:
          '@id': defaultDriveCommand
          kP: 0.003
          kI: 0.0
          kD: 0.05
          absoluteTolerance: 0
          deadband: 2
          maxAngularVelToEnterLoop: 3
          inverted: false
          highGearAngularCoefficient: 3
          rampComponent:
            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.RampComponent:
              maxIncreasePerSecond: 3
              maxDecreasePerSecond: 1.5
          driveStraightLoopEntryTimer:
            '@id': driveStraightLoopEntryTimer
            bufferTimeSeconds: 0.15
          subsystem:
            org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
              drive
          oi:
            org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad:
              '@id': oi
              gamepad:
                org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
                  '@id': driverGamepad
                  port: 1
              rotThrottle:
                org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                  &rotThrottle
                  '@id': rotThrottle
                  stick: driverGamepad
                  axis: 0
                  smoothingTimeSecs: 0.04
                  deadband: 0.08
                  inverted: false
                  polynomial:
                    org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                      '@id': rotPoly
                      powerToCoefficientMap: !!map
                        1: .5
                        3: .5
                  scale: .7
              fwdThrottle:
                org.usfirst.frc.team449.robot.oi.throttles.ThrottleSum:
                  '@id': fwdThrottle
                  throttles:
                    - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                        <<: *rotThrottle
                        '@id': posThrottle
                        axis: 3
                        inverted: false
                        deadband: 0.05
                        polynomial:
                          org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                            '@id': posPoly
                            powerToCoefficientMap: !!map
                              1: 2
                              3: 1
                    - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
                        <<: *rotThrottle
                        '@id': negThrottle
                        axis: 2
                        inverted: true
                        deadband: 0.05
                        polynomial:
                          org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                            '@id': negPoly
                            powerToCoefficientMap: !!map
                              1: 2
                              3: 1
              invertDPad: false
              dPadShift: 0.1
              turnInPlaceRotScale: 0.5
              rescaleOutputs: true
              scaleRotByFwdPoly:
                org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
                  '@id': scaleRotByFwdPoly
                  powerToCoefficientMap: !!map
                    0.5: 0.4
                    0: 0.2
                    #1 : 0.25
                    #2: 0.25
          autoshiftComponent:
            '@id': autoshiftComponent
            upshiftSpeed: 4
            downshiftSpeed: 2.7
            upshiftDebouncer:
              '@id': upshiftDebouncer
              bufferTimeSeconds: 0.06
            upshiftFwdThresh: 0.4
  #BUTTONS
  buttons:
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': shooterStartButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              '@id': mechanismsJoystick
              port: 0
          buttonNumber: 1 #A
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.SpinUpThenShoot:
          '@id': shootCommand
          flywheel:
            org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
              shooterFlywheel
          feeder:
            org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
              feeder
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': shooterStopButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 2 #B
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.flywheel.commands.TurnAllOff:
          '@id': shooterStopCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.complex.shooter.LoggingFlywheel:
              shooterFlywheel
      action: WHEN_PRESSED
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': feederStopButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 3 #X
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.intake.commands.SetIntakeMode:
          '@id': feederStopCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.interfaces.intake.IntakeSimple:
              feeder
          mode: IN_SLOW
      action: WHEN_PRESSED


# UPDATER
updater:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
      - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
      - org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad: oi
      - org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS: navX
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP
