---
# WHETHER TO USE THE CAMERA SERVER
useCameraServer: false

# PDP
pdp:
  org.usfirst.frc.team449.robot.jacksonWrappers.PDP:
    '@id': PDP
    canID: 0
    voltagePerCurrentLinReg:
      bufferSize: 250
      rSquaredThreshhold: 0.75

# ROBOT SUBSYSTEMS
subsystems:
  # CLIMBER
  - org.usfirst.frc.team449.robot.subsystem.complex.climber.ClimberWinchingWithArm:
      '@id': climber
      motorSubsystem:
        org.usfirst.frc.team449.robot.subsystem.complex.climber.ClimberCurrentLimited:
          '@id': climberCurrentLimitSystem
          smartMotor:
            org.usfirst.frc.team449.robot.jacksonWrappers.FPSSparkMax:
              '@id': climberMotor
              port: 1
              enableBrakeMode: false
          maxPower: 0.1
          powerLimitTimer:
            '@id': climberLimitTimer
            bufferTimeSeconds: 1
      solenoidSubsystem:
        org.usfirst.frc.team449.robot.subsystem.interfaces.solenoid.SolenoidSimple:
          '@id': climberSolenoidSystem
          piston:
            '@id': climberSolenoid
            module: 0
            forward: 1
            reverse: 2

# COMMANDS
commands:
  #BUTTONS
  buttons:
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': climberOffButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              '@id': mechanismsJoystick
              port: 2 #TODO
          buttonNumber: 1 #A
      action: WHEN_PRESSED
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.climber.commands.SetClimberWithArmState:
          '@id': climberOffCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.complex.climber.ClimberWinchingWithArm:
              climber
          state: "OFF"
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': climberRaiseButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 2 #B
      action: WHEN_PRESSED
      command:
        org.usfirst.frc.team449.robot.subsystem.interfaces.climber.commands.SetClimberWithArmState:
          '@id': climberRaiseCommand
          subsystem:
            org.usfirst.frc.team449.robot.subsystem.complex.climber.ClimberWinchingWithArm:
              climber
          state: "RAISE"
    - button:
        org.usfirst.frc.team449.robot.oi.buttons.SimpleButton:
          '@id': climberLowerButton
          joystick:
            org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
              mechanismsJoystick
          buttonNumber: 3 #X
      action: WHEN_PRESSED
      command:
        #TODO check this
        org.usfirst.frc.team449.robot.commands.general.ConditionalCommandFunctional:
          onTrue:
            org.usfirst.frc.team449.robot.subsystem.interfaces.climber.commands.SetClimberWithArmState:
              '@id': climberLowerCommand
              subsystem:
                org.usfirst.frc.team449.robot.subsystem.complex.climber.ClimberWinchingWithArm:
                  climber
              state: LOWER
          booleanSupplier:
            org.usfirst.frc.team449.robot.commands.general.InstanceMethodBooleanSupplier:
              source: climber
              methodName: winchUpEnabled

  # DEFAULT COMMANDS
  defaultCommands:
      # DEFAULT DRIVE COMMAND
#      - subsystem:
#          org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
#            drive
#        command:
#          org.usfirst.frc.team449.robot.commands.multiInterface.drive.UnidirectionalNavXShiftingDefaultDrive:
#            '@id': defaultDriveCommand
#            kP: 0.003
#            kI: 0.0
#            kD: 0.05
#            absoluteTolerance: 0
#            deadband: 2
#            maxAngularVelToEnterLoop: 3
#            inverted: false
#            highGearAngularCoefficient: 3
#            rampComponent:
#              org.usfirst.frikc.team449.robot.generalInterfaces.doubleUnaryOperator.RampComponent:
#                maxIncreasePerSecond: 3
#                maxDecreasePerSecond: 1.5
#            driveStraightLoopEntryTimer:
#              '@id': driveStraightLoopEntryTimer
#              bufferTimeSeconds: 0.15
#            subsystem:
#              org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable:
#                drive
#            oi:
#              org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad:
#                '@id': oi
#                gamepad:
#                  org.usfirst.frc.team449.robot.jacksonWrappers.MappedJoystick:
#                    '@id': driverGamepad
#                    port: 1
#                rotThrottle:
#                  org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
#                    &rotThrottle
#                    '@id': rotThrottle
#                    stick: driverGamepad
#                    axis: 0
#                    smoothingTimeSecs: 0.04
#                    deadband: 0.08
#                    inverted: false
#                    polynomial:
#                      org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                        '@id': rotPoly
#                        powerToCoefficientMap: !!map
#                          1: .5
#                          3: .5
#                    scale: .7
#                fwdThrottle:
#                  org.usfirst.frc.team449.robot.oi.throttles.ThrottleSum:
#                    '@id': fwdThrottle
#                    throttles:
#                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
#                          <<: *rotThrottle
#                          '@id': posThrottle
#                          axis: 3
#                          inverted: false
#                          deadband: 0.05
#                          polynomial:
#                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                              '@id': posPoly
#                              powerToCoefficientMap: !!map
#                                1: 2
#                                3: 1
#                      - org.usfirst.frc.team449.robot.oi.throttles.ThrottlePolynomial:
#                          <<: *rotThrottle
#                          '@id': negThrottle
#                          axis: 2
#                          inverted: true
#                          deadband: 0.05
#                          polynomial:
#                            org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                              '@id': negPoly
#                              powerToCoefficientMap: !!map
#                                1: 2
#                                3: 1
#                invertDPad: false
#                dPadShift: 0.1
#                turnInPlaceRotScale: 0.5
#                rescaleOutputs: true
#                scaleRotByFwdPoly:
#                  org.usfirst.frc.team449.robot.generalInterfaces.doubleUnaryOperator.Polynomial:
#                    '@id': scaleRotByFwdPoly
#                    powerToCoefficientMap: !!map
#                      0.5: 0.4
#                      0: 0.2
#                      #1 : 0.25
#                      #2: 0.25
#            autoshiftComponent:
#              '@id': autoshiftComponent
#              upshiftSpeed: 4
#              downshiftSpeed: 2.7
#              upshiftDebouncer:
#                '@id': upshiftDebouncer
#                bufferTimeSeconds: 0.06
#              upshiftFwdThresh: 0.4
#    autoStartupCommand:
#      org.usfirst.frc.team449.robot.commands.multiInterface.drive.RamseteControllerUnidirectionalDrive:
#        '@id':testDriveCommand
#        drivetrain:
#          org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
#        P: 0.15
#        D: 0

# UPDATER
updater:
  org.usfirst.frc.team449.robot.other.Updater:
    '@id': updater
    updatables:
#      - org.usfirst.frc.team449.robot.drive.unidirectional.DriveUnidirectionalWithGyroShiftable: drive
#      - org.usfirst.frc.team449.robot.oi.unidirectional.arcade.OIArcadeWithDPad: oi
#      - org.usfirst.frc.team449.robot.jacksonWrappers.MappedAHRS: navX
      - org.usfirst.frc.team449.robot.jacksonWrappers.PDP: PDP

